#!/usr/bin/env node
// Derive TQ ticket status from GitHub PRs — the single computation.
//
// Status is NOT stored by hand anywhere. It is computed from:
//   1. the TQ-NNN artifacts in docs/plan/   (the work-list + titles)
//   2. `gh pr list --state all`             (what has actually shipped)
//
// A PR implements a ticket when its title ends with a `(TQ-NNN)` tag — the
// going-forward convention (e.g. `feat(combat): … (TQ-007)`). A bare mention
// elsewhere in the title (`docs: fix TQ-004 misattribution`) is prose, not an
// implementation, and is deliberately NOT matched. A ticket is `merged` if a
// merged PR implements it, `in progress` if an open PR does, else `todo`.
// Pre-convention implementing PRs that predate the trailing-tag rule are mapped
// explicitly in OVERRIDES below (append-only; new PRs should self-describe).
//
// Usage:
//   node scripts/status.mjs            # print the table to stdout
//   node scripts/status.mjs --write    # regenerate docs/plan/STATUS.md
//
// Requires the GitHub CLI (`gh`) to be installed and authenticated.

import { execSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PLAN_DIR = join(ROOT, 'docs', 'plan');
const STATUS_FILE = join(PLAN_DIR, 'STATUS.md');

// Pre-convention implementing PRs (before the trailing-`(TQ-NNN)` rule). These
// tagged the ticket at the start (`PR-006: …`) or carried no tag at all. PR
// number -> ticket id(s). Append-only; new PRs self-describe via a trailing tag.
const OVERRIDES = {
  3: ['TQ-000'], // PR-000: project scaffold
  5: ['TQ-001'], // PR-001: tile renderer + state + camera
  7: ['TQ-002', 'TQ-003'], // PR-002 + PR-003: game loop + movement
  8: ['TQ-004'], // seeded RNG module (rng.ts lives in TQ-004)
  9: ['TQ-005'], // PR-005 (core): enemy data model
  10: ['TQ-006'], // PR-006: combat engine core
  12: ['TQ-004'], // PR-004: procedural world generator
  13: ['TQ-004'], // PR-004 follow-up: seed reproducibility
  29: ['TQ-005'], // pure enemy AI stepping
};

/** Pad a numeric ticket id to the canonical 3-digit `TQ-NNN`. */
function tid(n) {
  return `TQ-${String(n).padStart(3, '0')}`;
}

/** Every ticket from the plan folder, with its human title from line 1. */
function readTickets() {
  return readdirSync(PLAN_DIR)
    .filter((f) => /^TQ-\d+.*\.md$/.test(f))
    .sort()
    .map((file) => {
      const first = readFileSync(join(PLAN_DIR, file), 'utf8').split('\n')[0];
      const m = first.match(/^#\s*(TQ-\d+)\s*[—-]\s*(.+)$/);
      const id = m ? m[1] : file.replace(/\.md$/, '');
      const title = m ? m[2].trim() : '';
      return { id, title, file };
    });
}

/** Pull every PR (any state) as {number, title, state}. */
function readPrs() {
  const raw = execSync('gh pr list --state all --limit 300 --json number,title,state', {
    cwd: ROOT,
    encoding: 'utf8',
  });
  return JSON.parse(raw);
}

/** Ticket the PR implements: explicit override, else a trailing `(TQ-NNN)` tag. */
function ticketsForPr(pr) {
  if (OVERRIDES[pr.number]) return OVERRIDES[pr.number];
  const m = pr.title.match(/\((?:TQ|PR)-0*(\d+)[a-z]?\)\s*$/i);
  return m ? [tid(Number(m[1]))] : [];
}

function computeState(prs) {
  // ticket id -> { merged:[#], open:[#] }
  const byTicket = new Map();
  for (const pr of prs) {
    const bucket = pr.state === 'MERGED' ? 'merged' : pr.state === 'OPEN' ? 'open' : null;
    if (!bucket) continue; // ignore CLOSED-unmerged
    for (const id of ticketsForPr(pr)) {
      if (!byTicket.has(id)) byTicket.set(id, { merged: [], open: [] });
      byTicket.get(id)[bucket].push(pr.number);
    }
  }
  return byTicket;
}

function stateFor(entry) {
  if (!entry) return 'todo';
  if (entry.merged.length) return 'merged';
  if (entry.open.length) return 'in progress';
  return 'todo';
}

function render(tickets, byTicket) {
  const rows = tickets.map((t) => {
    const entry = byTicket.get(t.id);
    const state = stateFor(entry);
    const asc = (a, b) => a - b;
    const prs = entry
      ? [
          ...entry.merged.sort(asc).map((n) => `#${n}`),
          ...entry.open.sort(asc).map((n) => `#${n} (open)`),
        ].join(', ')
      : '—';
    return { id: t.id, title: t.title, state, prs: prs || '—' };
  });

  const counts = rows.reduce((a, r) => ((a[r.state] = (a[r.state] ?? 0) + 1), a), {});
  const lines = [
    '<!-- GENERATED by scripts/status.mjs — do not hand-edit. Run: node scripts/status.mjs --write -->',
    '# Status — derived from PRs',
    '',
    'Single source of truth for ticket state. **Do not edit by hand** — regenerate with',
    '`node scripts/status.mjs --write`. State is computed from merged/open PRs (matched to',
    'tickets by the `TQ-NNN` tag in each PR title), never stored manually.',
    '',
    `**${counts.merged ?? 0} merged · ${counts['in progress'] ?? 0} in progress · ${counts.todo ?? 0} todo**`,
    '',
    '| TQ | Title | State | PRs |',
    '|----|-------|-------|-----|',
    ...rows.map((r) => `| ${r.id.replace('TQ-', '')} | ${r.title} | ${r.state} | ${r.prs} |`),
    '',
  ];
  return lines.join('\n');
}

const tickets = readTickets();
const byTicket = computeState(readPrs());
const out = render(tickets, byTicket);

if (process.argv.includes('--write')) {
  writeFileSync(STATUS_FILE, out);
  process.stdout.write(`wrote ${STATUS_FILE}\n`);
} else {
  process.stdout.write(out + '\n');
}
